Store table by name, if provided
Xalgorithms/xadf-jobs pull request #43
Opened 2018-02-28 10:20 UTC by hpilosyan

Change-Id: I5fbd39f11061a01030d683b99efc364fd14c0748

2018-02-28 11:11 UTC, karfai requested changes
Make a more detailed commit comment to explain why we should do this change.

2018-03-11 23:40 UTC, karfai commented
Have the changes ever been made to this PR?

2018-03-12 15:36 UTC, hpilosyan commented
Commit message was improved with an explanation of a change

2018-03-13 01:14 UTC, karfai approved these changes

2018-03-13 01:14 UTC, merged